# fly.toml app configuration file generated for api-habit-helper on 2023-06-01T04:19:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-habit-helper"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
